import { pageMetadata } from "@/lib/metadata";
import CraftPhoto from "../_components/CraftPhoto";
import { hasamiPhotos } from "./hasamiPhotos";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import BackToContents from "../_components/BackToContents";
import CraftProcess from "../_components/CraftProcess";
import VisitLinks from "../_components/VisitLinks";

export const metadata: Metadata = pageMetadata({
  title: "Hasami Ware (波佐見焼): Everyday Porcelain, History & Travel Guide",
  description: "Explore Hasami Ware through its materials, specialist workshops, everyday tableware, and connections with Arita, with places to visit and a buying guide.",
  path: "/en/crafts/hasami-ware",
  article: true,
});

// Editorial basis: content/research/hasami.md.
const sections = [
  ["overview", "Overview"], ["history", "History"],
  ["why-here", "Why Hasami?"], ["hasami-and-arita", "Hasami, Arita, and Imari"],
  ["characteristics", "Characteristics"], ["production", "How Hasami Ware Is Made"],
  ["visit", "Where to Experience Hasami Ware"], ["today", "Hasami Ware Today"],
  ["buying", "Buying Guide"], ["faq", "FAQ"], ["sources", "Sources & Further Reading"],
] as const;
const sources = [
  ["Hasami Town History and Culture Museum — History of Hasami Ware", "https://www.town.hasami.lg.jp/rekishi/kiji0031891/index.html", "Archaeological chronology, early porcelain, changing markets, and modern production."],
  ["Hasami Town — Hasami Ware", "https://www.town.hasami.lg.jp/kiji0031619/", "The traditional origin account, everyday tableware, and specialist producers."],
  ["Nagasaki Prefecture — Historic Hasami Kiln Sites", "https://www.pref.nagasaki.jp/bunkadb/index.php/view/406", "Quarries, large climbing kilns, and the Omura Domain's administrative office."],
  ["Hasami Ware Promotion Association — How It Is Made", "https://hasamiyaki.com/process/", "Mold makers, body makers, kilns, glaze suppliers, and trading companies."],
  ["Nagasaki Museum of History and Culture — Mikawachi and Hasami Exhibition", "https://www.nmhc.jp/cms/wp-content/uploads/back_number_link/exhibition/2016/mikawachi_hasami/index.html", "Domestic everyday wares and the history of the Hizen ceramic region."],
  ["Nagasaki Prefectural Art Museum — Crafts of Nagasaki", "https://www.nagasaki-museum.jp/archives/past-exhibition/21213", "Early fine celadon as well as mass-produced everyday vessels."],
  ["Hasami Ware Promotion Association — History", "https://hasamiyaki.com/history/", "Kurawanka bowls and the changing uses of Hasami ceramics."],
  ["SMRJ — Saikai Toki and the Next Generation", "https://shoukei9.smrj.go.jp/598/", "A business interview about branding, design collaboration, and regional production; historical recollections are treated as testimony."],
  ["Yusuke Inoue — Regional Identity and Rhetorical History (2026)", "https://doi.org/10.20627/jsim.45.1_43", "Research on Hasami's identity, including a distinction between origin-labeling negotiations and later accounts of that transition (pp. 55–56)."],
  ["HASAMI PORCELAIN — ORIGINAL", "https://hasami-porcelain.com/en/original/", "A particular contemporary brand and its semi-porcelain collection, not a definition of the entire region."],
  ["Nagasaki Prefecture — 2024 Northern Region Handbook", "https://www.pref.nagasaki.lg.jp/shared/uploads/2024/07/1720750650.pdf", "Industrial trends and statistical definitions; the figures are not a current count of all Hasami businesses."],
  ["Hasami Town — Fiscal 2025 Local Development Fund Projects", "https://www.town.hasami.lg.jp/kiji0031811/index.html", "Research into the disposal and reuse of waste plaster molds."],
  ["Nishinohara — About", "https://24nohara.jp/about/", "The former ceramics factory and the reuse of its buildings."],
  ["Maruhiro — MONOHARA 21cm Bowl", "https://www.hasamiyaki.jp/en/item/21cm-bowl/", "A product-specific example of material and heat-use instructions."],
  ["Imari City — About Ko-Imari", "https://www.city.imari.lg.jp/21096.htm", "The historical trade name, its connection with Imari port, and production centers including Hasami."],
] as const;
const prose = "mt-5 space-y-6 leading-8 text-stone-700";
const card = "rounded-lg border border-stone-200 bg-white p-6";
const link = "underline underline-offset-4 hover:text-stone-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]";
function Section({ id, children }: { id: (typeof sections)[number][0]; children: ReactNode }) {
  return <section id={id} aria-labelledby={`${id}-heading`} className="scroll-mt-6"><h2 id={`${id}-heading`} className="text-3xl font-semibold">{sections.find(section => section[0] === id)?.[1]}</h2>{children}<BackToContents /></section>;
}
function Reading({ ids }: { ids: number[] }) {
  return <p className="mt-6 text-sm leading-7 text-stone-600">Reading for this section: {ids.map((id, index) => <span key={id}>{index > 0 && "; "}<a href={`#source-${id}`} className={link}>{sources[id - 1][0]}</a></span>)}.</p>;
}
const steps = [
  { number: "01", title: "Preparing the Material", shortLabel: "Material", summary: "Prepare clay for the intended vessel.", description: "Raw material is processed into a workable ceramic body. Material preparation and the choice of body precede forming; the finished vessel depends on these decisions as well as its decoration." },
  { number: "02", title: "Making the Mold", shortLabel: "Mold", summary: "Turn a design into a repeatable form.", description: "Specialist mold makers translate a design into plaster molds. Different molds suit different forming methods, allowing a shape to be made repeatedly while serving the practical needs of the workshop." },
  { number: "03", title: "Forming and Drying", shortLabel: "Form & dry", summary: "Body makers shape the vessel.", description: "Body makers use methods such as powered forming with a plaster mold or slip casting, in which liquid clay enters a mold. The shaped bodies are dried before the next stages. The method depends on the object; not every Hasami piece follows the same route." },
  { number: "04", title: "Bisque Firing", shortLabel: "Bisque", summary: "Prepare the body for decoration.", description: "An initial firing gives the dried body strength for handling and subsequent work. The local promotion association gives around 900°C as an example, rather than a universal specification for every workshop." },
  { number: "05", title: "Decoration and Glazing", shortLabel: "Decorate & glaze", summary: "Add the planned surface treatment.", description: "For underglaze-decorated ware, painting or printing precedes glazing. Hand-painted lines, filled areas, stamps, and pad printing offer different ways of applying a design. Glaze suppliers also take part in the regional network. An undecorated design does not need this painting stage." },
  { number: "06", title: "High Firing", shortLabel: "High firing", summary: "Fire the body and glaze.", description: "The glazed pieces are fired and then cooled. Around 1,300°C is the association's example for the main firing; actual schedules depend on the body, glaze, and product. Designs with overglaze decoration need additional work and firing after this stage." },
  { number: "07", title: "Inspection and Distribution", shortLabel: "Inspect & deliver", summary: "Connect the workshop to the table.", description: "Finished pieces are checked and prepared for sale. Trading companies can coordinate orders, production, inspection, and delivery as well as develop markets. A name on a shop label may therefore represent a collaboration among several specialists." },
];
const places = [
  { name: "Hasami Town History and Culture Museum", description: "Start here for the town's history and the context behind its ceramics. A useful choice if you want to understand the place before choosing a piece.", website: "https://www.town.hasami.lg.jp/rekishi/default.html", mapQuery: "波佐見町歴史文化交流館", note: "Check current exhibitions, opening days, and available language support." },
  { name: "Togeikan and Kurawankan", description: "The ceramics center brings historical objects and production displays together with opportunities to browse contemporary wares. It is a practical starting point for a first visit.", website: "https://www.nagasaki-tabinet.com/guide/467", mapQuery: "波佐見町陶芸の館 くらわん館", note: "Confirm any hands-on activities, booking requirements, and collection or shipping arrangements in advance." },
  { name: "Nakaoyama", description: "Walk among kiln sites, brick chimneys, workshops, and narrow streets. The hillside setting makes the relationship between terrain and ceramic production easier to understand.", website: "https://www.nagasaki-tabinet.com/guide/60335", mapQuery: "波佐見町 中尾山交流館", note: "This is a working neighborhood. Check shop opening days and ask before entering workshops or photographing production." },
  { name: "Nishinohara", description: "A former ceramics factory has become a place for shops, food, and creative activity. Visit for the relationship between industrial buildings and their contemporary uses.", website: "https://24nohara.jp/about/", mapQuery: "波佐見町 西の原", note: "Opening days vary by business; check the places you want to visit individually." },
  { name: "Hasami Pottery Festival", description: "The annual event during Golden Week, Japan’s holiday period in late April and early May, brings together many kilns and trading companies. It offers a concentrated introduction to the variety of wares sold in the region.", website: "https://hasamitoukimatsuri.com/", mapQuery: "波佐見町 やきもの公園", note: "Confirm the next event's dates, venues, transport, and workshop schedule. Festival arrangements differ from an ordinary visit." },
];
const faqs = [
  ["Is Hasami Ware pottery or porcelain?", "The region is particularly known for porcelain tableware, but material varies by product. For example, the ORIGINAL line from the specific brand HASAMI PORCELAIN is described by its maker as semi-porcelain. The brand and the production region are not the same thing."],
  ["Is Hasami Ware the same as Arita Ware?", "They are neighboring production regions with closely connected commercial histories. Hasami products have circulated through Arita's trading networks, but the present-day names should not be treated as interchangeable. Check the maker and origin of an individual piece."],
  ["What are kurawanka bowls?", "The name is associated with affordable everyday bowls and with vendors serving travelers on boats on the Yodo River. Hasami was an important producer. The term should not be taken to mean that every such bowl came from Hasami or was disposable."],
  ["Is HASAMI PORCELAIN the name for all Hasami ceramics?", "No. It is a particular contemporary brand. Hasami Ware covers a broader range of makers, designs, and products."],
  ["Is all Hasami Ware handmade?", "That word can hide different processes. Mold making, powered forming, casting, hand painting, and printing can all involve specialist skills. Ask how the particular piece was formed and decorated instead of treating handmade as a single technical category."],
  ["Can Hasami Ware go in a microwave or dishwasher?", "Follow the instructions for the specific product. Suitability varies with material, decoration, and design. Microwave approval does not automatically mean approval for an oven or direct flame."],
  ["Can I visit Hasami outside the pottery festival?", "Yes. Museums, shops, and the pottery district offer reasons to visit beyond the festival. Check individual opening days and transport, and book workshop activities in advance where required."],
];

export default function HasamiWarePage() {
  return <main className="mx-auto max-w-4xl px-6 py-12 sm:py-20">
    <header><p className="text-sm uppercase tracking-[0.25em] text-stone-500">Nagasaki · Ceramics</p><h1 className="mt-4 text-4xl font-semibold sm:text-5xl">Hasami Ware <span className="whitespace-nowrap">(波佐見焼)</span></h1><p className="mt-6 max-w-3xl text-xl leading-9 text-stone-600">Behind an everyday bowl is a town of specialists—shaping, firing, and finding new ways to bring ceramics into daily life.</p></header>
    <CraftPhoto {...hasamiPhotos.tableware} layout="wide" preload />
    <nav id="contents" aria-label="Article contents" className="mt-12 scroll-mt-6 border-y border-stone-200 py-6"><p className="mb-4 text-sm font-semibold uppercase tracking-wider">Contents</p><ul className="grid gap-2 sm:grid-cols-2">{sections.map(([id, title]) => <li key={id}><a href={`#${id}`} className="inline-flex min-h-11 items-center text-stone-600 hover:text-stone-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">{title}</a></li>)}</ul></nav>
    <article className="space-y-20 pt-16">
      <Section id="overview"><div className={prose}><p>Hasami Ware is associated with Hasami, an inland town in Nagasaki Prefecture in northwestern Kyushu. It is especially known for everyday porcelain: bowls, plates, cups, and other objects made to be used regularly. Its range extends beyond a single color, pattern, or brand.</p><p>A finished cup may be the work of several businesses. Mold makers, body makers, kilns, glaze suppliers, and trading companies contribute different skills. This regional network is a useful starting point for understanding how Hasami makes familiar objects on a large scale.</p></div><Reading ids={[2, 4]} /></Section>
      <Section id="history"><div className={prose}><p>The traditional origin account connects Hasami&apos;s kilns with Korean potters brought to Japan following the Japanese invasions of Korea in the 1590s. Hasami Town associates a beginning in 1599 with potters including Ri Yukei. This account should be read in the context of war and the movement of people, rather than as a simple story of voluntary artistic exchange.</p><p>The town museum&apos;s archaeological outline presents a gradual development: pottery around 1600, early porcelain in the 1610s–1620s, and more substantial porcelain production at Mitsunomata from the 1630s. The start of pottery making and the emergence of a porcelain industry are different milestones.</p><p>Early Hasami included fine celadon—ceramics with a green or blue-green glaze—for affluent buyers, as well as wares later made for overseas markets. By the late seventeenth century, domestic everyday bowls and dishes became an important direction. Hasami&apos;s history cannot be reduced to inexpensive tableware from the very beginning.</p><p>Changes continued into modern times, with new forming and decorating methods and different kiln fuels. Today&apos;s tableware belongs to that history of adapting production to what people need.</p></div><Reading ids={[1, 2, 5, 6]} /></Section>
      <Section id="why-here"><div className={prose}><p>Porcelain stone at Mitsunomata helped provide a material basis for the industry. Sloping ground in districts such as Nakaoyama suited climbing kilns, whose chambers rose along the hillside. The surviving quarry and kiln sites allow visitors to connect the material with the place where it was fired.</p><p>The Omura Domain also shaped production. Its Sarayama administrative office, established in 1666, oversaw matters including product inspection and the collection of levies. Ceramic production was an organized regional activity, supported and controlled through institutions as well as workshop knowledge.</p><p>Large kilns later helped reduce the cost of producing everyday vessels. Yet resources and equipment alone were not enough: the industry also needed skilled workers and connections to buyers. Hasami is a story of those conditions coming together.</p></div><CraftPhoto {...hasamiPhotos.nakaoyama} layout="wide" /><Reading ids={[3]} /></Section>
      <Section id="hasami-and-arita"><div className={prose}><p>Hasami in Nagasaki and neighboring Arita in Saga belong to the wider historical Hizen ceramic region, spanning parts of present-day Saga and Nagasaki prefectures. Their production and trading networks have long been connected. Hasami-made products also circulated as Arita Ware, so the name encountered by a buyer did not always make the place of manufacture visible.</p><p>Historical Imari is another layer: a trade-related name encompassing porcelain from more than one Hizen production center. It should not be read as a guarantee that every object was made in present-day Arita or Imari. Our <Link href="/en/crafts/arita-ware#arita-and-imari" className={link}>guide to Arita, Imari, and Ko-Imari</Link> explains these overlapping names.</p><p>The name Hasami Ware predates its recent popularity: the town records its designation as a traditional craft in 1978. In the early 2000s, industry discussions about origin labeling helped bring the relationship between production and naming into focus. Contemporary branding has made the place of manufacture more visible to buyers, but this was a commercial transition, not the sudden birth of a new craft.</p></div><aside className="mt-8 border-l-2 border-stone-300 pl-6"><h3 className="text-sm font-semibold uppercase tracking-wider text-stone-500">A useful distinction</h3><p className="mt-3 leading-8 text-stone-700">Hasami and Arita are not two price levels of the same product. Both encompass varied work. Ask where a piece was made, who made it, and how it reached the shop.</p></aside><Reading ids={[1, 8, 9, 15]} /></Section>
      <Section id="characteristics"><p className={prose}>Look for the relationship between a vessel&apos;s appearance and its job. These examples are ways into the region&apos;s history, rather than a fixed list of styles.</p><div className="mt-8 grid gap-6 sm:grid-cols-2">{[
        ["Celadon and Blue-and-White", "Early celadon reveals a more refined side of Hasami's history. Blue-and-white decoration offers another way to study the relationship between painted motifs and a vessel's shape."],
        ["Kurawanka Bowls", "These everyday bowls are associated with affordable tableware and the calls of vendors serving travelers on the Yodo River. Their importance lies in widespread use, not simply in one decorative pattern."],
        ["Komprador Bottles", "Bottles carrying sake or soy sauce through Nagasaki connect ceramics with the transport of other goods. A vessel could be part of overseas trade without being sold primarily as a decorative object."],
        ["Contemporary Tableware", "Compare handles, rims, surfaces, and how pieces stack. Quiet colors and modular shapes are one contemporary approach; bright decoration and other forms also belong to Hasami."],
      ].map(([title, text]) => <div key={title} className={card}><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-stone-600">{text}</p></div>)}</div><CraftPhoto {...hasamiPhotos.bottles} layout="wide" /><Reading ids={[2, 6, 7, 10]} /></Section>
      <Section id="production"><p className={prose}>The sequence below follows a typical mold-based porcelain route. Read it as a collaboration between specialists: some businesses handle several stages, while others concentrate on one.</p><CraftProcess id="hasami-process" eyebrow="A town of specialists" title="From Material to the Everyday Table" steps={steps} caveat="A general outline, not a recipe for every product. Forming methods, decoration, and firing schedules vary; overglaze decoration adds further stages." note="Repeatable forms still depend on knowledge and judgment. The craft includes making the mold, controlling the body and glaze, inspecting the result, and coordinating the people who bring it to the user." /><Reading ids={[4, 13]} /></Section>
      <Section id="visit"><p className={prose}>Combine historical displays with time in a working pottery district. Check current transport and opening days; festival shuttles and activities are not necessarily available year-round.</p><div className="mt-8 grid gap-6 sm:grid-cols-2">{places.map(place => <div key={place.name} className={card}><h3 className="text-xl font-semibold">{place.name}</h3><p className="mt-3 leading-7 text-stone-600">{place.description}</p><VisitLinks {...place} /></div>)}</div></Section>
      <Section id="today"><div className={prose}><p>Contemporary brands give buyers new ways to recognize Hasami&apos;s production. HASAMI PORCELAIN, for example, uses modular forms and emphasizes material and texture. Its ORIGINAL collection is described as semi-porcelain. It is one brand within a wider region, rather than the name for all Hasami ceramics.</p><p>Design collaboration can link commercial planning with the skills of several local manufacturers. The reuse of former factory buildings at Nishinohara offers another connection between the industry and people visiting the town.</p><p>Visibility does not remove the pressures on production. Prefectural reporting describes long-term market challenges and the disruption of the pandemic. Hasami Town has also supported research into waste plaster molds. The future of everyday tableware depends on sustaining the work and resources behind it, as well as developing appealing designs.</p></div><Reading ids={[8, 10, 11, 12, 13]} /></Section>
      <Section id="buying"><div className={prose}><p>Start with a role: a bowl for breakfast, a mug for coffee, or a plate that fits your usual meals. Check weight, capacity, the feel of the rim, and the space needed in your cupboard. If you want a set, ask whether the range is likely to remain available for later additions.</p><p>Ask about the process without assuming that one method always means better quality. A molded body, a printed pattern, and a hand-painted detail represent different choices. In a region built on collaboration, the selling brand and the manufacturing workshop may also have different names.</p><p>Read the care instructions for the particular item. Maruhiro&apos;s MONOHARA 21cm Bowl, for example, is listed as suitable for an oven, microwave, and dishwasher, but not direct flame. Those permissions do not apply automatically to other Hasami products. Check decoration, surface treatment, and any accompanying wooden parts separately.</p><p>For a gift or a purchase to take overseas, ask about protective packaging, replacement options, and shipping. If you make a piece in a workshop, confirm when drying and firing will be finished before planning to take it home.</p></div><Reading ids={[4, 14]} /></Section>
      <Section id="faq"><div className="mt-8 divide-y divide-stone-200 border-y border-stone-200">{faqs.map(([question, answer]) => <details key={question} className="py-4"><summary className="min-h-11 cursor-pointer py-2 font-semibold leading-7 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">{question}</summary><p className="mt-4 leading-8 text-stone-700">{answer}</p></details>)}</div></Section>
      <Section id="sources"><p className={prose}>This guide draws on museum, municipal, prefectural, industry, academic, and maker sources. Traditional origin accounts and later business recollections are distinguished from archaeological and documentary research. Most local sources are in Japanese.</p><ul className="mt-8 space-y-6">{sources.map(([title, url, note], index) => <li id={`source-${index + 1}`} key={url} className="scroll-mt-6 border-l-2 border-stone-200 pl-4"><a href={url} target="_blank" rel="noopener noreferrer" className={`inline-block py-2 font-medium leading-7 ${link}`}>{title} <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a><p className="mt-2 text-sm leading-6 text-stone-600">{note}</p></li>)}</ul><p className="mt-8 text-sm leading-7 text-stone-600">Research reviewed October 2026. Confirm current visitor arrangements and product-care instructions with the relevant institution or maker.</p></Section>
    </article>
    <aside aria-label="Related craft guides" className="mt-16 border-t border-stone-200 pt-8"><h2 className="text-xl font-semibold">Explore Other Ceramic Traditions</h2><p className="mt-4 leading-7 text-stone-700">Choosing between the two neighboring regions? <a href="/en/crafts/arita-vs-hasami" className="underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">Compare Arita and Hasami Ware</a> through their shared history, making, and what to look for when buying or visiting.</p><div className="mt-4 flex flex-wrap gap-6"><Link className={link} href="/en/crafts/arita-ware">Arita Ware →</Link><Link className={link} href="/en/crafts/kutani-ware">Kutani Ware →</Link><Link className={link} href="/en/crafts/shigaraki-ware">Shigaraki Ware →</Link><Link className={link} href="/en/crafts">All crafts →</Link></div></aside>
  </main>;
}
