import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { pageMetadata } from "@/lib/metadata";
import CraftPhoto from "../_components/CraftPhoto";
import { yamanakaPhotos } from "./yamanakaPhotos";
import BackToContents from "../_components/BackToContents";
import CraftProcess from "../_components/CraftProcess";
import VisitLinks from "../_components/VisitLinks";

export const metadata: Metadata = pageMetadata({
  title: "Yamanaka Lacquerware (山中漆器): Woodturning, History & Travel Guide",
  description: "Discover Yamanaka Lacquerware through woodturning, hot-spring trade, specialist workshops, and contemporary design, with places to visit and practical buying advice.",
  path: "/en/crafts/yamanaka-lacquerware",
  article: true,
});

// Editorial basis: content/research/yamanaka.md. Photo records: content/research/yamanaka-images.md.
const sections = [
  ["overview", "Overview"], ["history", "History"], ["why-here", "Why Yamanaka?"],
  ["materials", "Understanding Materials and Finishes"], ["characteristics", "Characteristics"],
  ["production", "How Yamanaka Lacquerware Is Made"], ["visit", "Where to Experience Yamanaka Lacquerware"],
  ["today", "Yamanaka Lacquerware Today"], ["buying", "Buying Guide"], ["faq", "FAQ"],
  ["sources", "Sources & Further Reading"],
] as const;
const sources = [
  ["Ishikawa Prefecture — Yamanaka Woodturning", "https://www.pref.ishikawa.lg.jp/kyoiku/bunkazai/mukei/k5.html", "The traditional origin account, historical development, and the use of both vertical and horizontal wood selection."],
  ["Yamanaka Lacquerware Industrial Technology Center — History", "https://yamanaka696.org/history/", "Woodturners, hot-spring visitors, incoming techniques, and care for wooden lacquerware."],
  ["Yamanaka Lacquerware Industrial Technology Center — Woodturning", "https://yamanaka696.org/woodturning/", "Tools, thin turning, fitted lids, and decorative turning."],
  ["Yamanaka Lacquerware Cooperative — Materials and Products", "https://www.yamanakashikki.com/onlinestore/", "Wooden and modern resin-bodied wares, with different coating and care requirements."],
  ["Yamanaka Lacquerware Cooperative — Production", "https://yamanakashikki.com/tradition/process/", "Separate production routes for wooden and modern wares, including coating and decoration."],
  ["Yamanaka Lacquerware Industrial Technology Center — Training", "https://yamanaka696.org/about/", "The training center and its woodturning, lacquer, and design curriculum."],
  ["Smart IoT Promotion Forum — Yamanaka Industry Case Study (2023)", "https://smartiot-forum.nict.go.jp/iot-val-team/iot-case/yamanakashikki/", "Specialist production, succession challenges, shared order management, and marketing."],
  ["Yamanaka Lacquerware Cooperative — The Next Generation", "https://yamanakashikki.com/tradition/future/", "Training, rental workshops, and lacquer-tree planting. Some figures describe 2020, not the present."],
  ["GATO MIKIO SHOUTEN — Yamanaka Lacquerware", "https://www.gatomikio.jp/about/", "A maker's account of woodturning, wiped lacquer, and design collaboration."],
  ["Yamanaka Lacquerware Cooperative — Urushiza (2024)", "https://www.yamanakashikki.com/article/3321", "Exhibitions, contemporary brands, and visitor activities; check current arrangements."],
  ["Kaga Onsen Official Tourism — Yamanaka Urushiza", "https://www.tabimati.net/spot/detail_130.html", "An introduction to the exhibition and shop, with visitor information."],
  ["CRAFTOUR — Workshop Visits", "https://www.craftour.jp/", "Guided experiences exploring Yamanaka's makers and production."],
] as const;
const link = "underline underline-offset-4 hover:text-stone-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]";
const prose = "mt-5 space-y-6 leading-8 text-stone-700";
const card = "rounded-lg border border-stone-200 bg-white p-6";
function Section({ id, children }: { id: (typeof sections)[number][0]; children: ReactNode }) {
  return <section id={id} aria-labelledby={`${id}-heading`} className="scroll-mt-6"><h2 id={`${id}-heading`} className="text-3xl font-semibold">{sections.find(section => section[0] === id)?.[1]}</h2>{children}<BackToContents /></section>;
}
function Reading({ ids }: { ids: number[] }) {
  return <p className="mt-6 text-sm leading-7 text-stone-600">Reading for this section: {ids.map((id, index) => <span key={id}>{index > 0 && "; "}<a href={`#source-${id}`} className={link}>{sources[id - 1][0]}</a></span>)}.</p>;
}
const steps = [
  { number: "01", title: "Selecting and Cutting the Wood", shortLabel: "Select wood", summary: "Plan the form around the material.", description: "The maker selects and cuts wood for the intended object. Vertical wood selection, or tate-kidori, is a characteristic approach in Yamanaka, but horizontal selection is also used where appropriate. The direction of the grain is one part of planning a stable, well-shaped vessel." },
  { number: "02", title: "Rough Turning and Drying", shortLabel: "Turn & dry", summary: "Leave room for the wood to move.", description: "The rough shape is turned before final finishing. Drying and further adjustment help the maker work with changes in the wood. Timing varies with the material and object; a drying period given for one production example is not a rule for every piece." },
  { number: "03", title: "Finishing the Form", shortLabel: "Refine the shape", summary: "Shape the surfaces and details.", description: "The woodturner refines the inside and outside, rim, and foot. Decorative turning can add fine grooves or other patterns at this stage. These details are cut into the body itself, so the shape and texture begin before a coating is applied." },
  { number: "04", title: "Choosing a Lacquer Finish", shortLabel: "Lacquer finish", summary: "Follow the chosen finishing route.", description: "For fuki-urushi, lacquer is applied and wiped back in repeated work that keeps the wood grain visible. A fully coated finish follows a different route, with ground preparation and layers of lacquer. These are alternative approaches, not two mandatory stages that every vessel passes through." },
  { number: "05", title: "Optional Decoration", shortLabel: "Add decoration", summary: "Complete the intended surface.", description: "Some pieces receive maki-e, in which a design made with lacquer carries decorative powders such as gold or silver. Others are complete with their turned texture or lacquer finish. Decoration depends on the design; it is not required on every Yamanaka vessel.", optional: true },
];
const places = [
  { name: "Yamanaka Urushiza", description: "Begin with displays and a shop bringing together different approaches to Yamanaka lacquerware. Compare the appearance and handling of everyday wares with more elaborate pieces.", website: "https://www.tabimati.net/spot/detail_130.html", mapQuery: "山中塗うるし座", note: "Check current opening days and activities. Ask which materials are used in any decorating experience." },
  { name: "Yamanaka Lacquerware Industrial Technology Center", description: "A place to understand the work behind the wooden body and the training of new makers. Woodturning visits and experiences offer a closer view of the tools and process.", website: "https://yamanaka696.org/", mapQuery: "石川県立山中漆器産業技術センター", note: "Arrange an experience in advance. Confirm language support and whether the activity includes a finished object to take home." },
  { name: "CRAFTOUR", description: "A guided workshop visit can connect the finished vessel with the specialists who make it. Consider this if conversations with makers are a priority for your trip.", website: "https://www.craftour.jp/", mapQuery: "CRAFTOUR 山中温泉", note: "Confirm availability, meeting point, price, and guiding language directly when booking. Workshops are working spaces." },
];
const faqs = [
  ["What is Yamanaka lacquerware made of?", "Check both the body and the coating. The region makes wooden lacquerware as well as modern resin-bodied products. Coatings can include natural urushi lacquer or other finishes, depending on the item."],
  ["Is all Yamanaka lacquerware made using tate-kidori?", "No. Vertical wood selection is a characteristic technique, but Ishikawa Prefecture's account also describes horizontal selection according to the object. It is a useful feature to understand, not a universal test of origin."],
  ["What is fuki-urushi?", "It is a finish made by applying lacquer and wiping it back, with repeated work that allows the wood grain to remain visible. It differs from a finish that covers the body with ground preparation and layers of lacquer."],
  ["Can I put it in a dishwasher or microwave?", "Follow the instructions for the particular product. Ordinary wooden lacquerware should be kept out of microwaves, dishwashers, and dish dryers. Some modern wares are specifically designed for such uses, but a resin body alone does not establish suitability."],
  ["Can visitors try woodturning?", "The local visitor information lists bookable woodturning experiences at the technology center. Confirm the current schedule, language arrangements, and whether a finished piece is included before visiting."],
  ["Is Yamanaka lacquerware the same as Kutani Ware?", "No. They offer different ways to explore the Kaga region: this guide concerns woodturning and lacquerware, while Kutani Ware is a ceramic tradition. A shared regional setting does not make their materials or processes interchangeable."],
];

export default function YamanakaLacquerwarePage() {
  return <main className="mx-auto max-w-4xl px-6 py-12 sm:py-20">
    <header><p className="text-sm uppercase tracking-[0.25em] text-stone-500">Ishikawa · Lacquerware</p><h1 className="mt-4 text-4xl font-semibold sm:text-5xl">Yamanaka Lacquerware <span className="whitespace-nowrap">(山中漆器)</span></h1><p className="mt-6 max-w-3xl text-xl leading-9 text-stone-600">A wooden bowl connects mountain workshops, hot-spring visitors, and generations of specialists who shape the surface beneath the lacquer.</p></header>
    <CraftPhoto {...yamanakaPhotos.cafe} layout="wide" preload />
    <nav id="contents" aria-label="Article contents" className="mt-12 scroll-mt-6 border-y border-stone-200 py-6"><p className="mb-4 text-sm font-semibold uppercase tracking-wider">Contents</p><ul className="grid gap-2 sm:grid-cols-2">{sections.map(([id, title]) => <li key={id}><a href={`#${id}`} className="inline-flex min-h-11 items-center text-stone-600 hover:text-stone-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">{title}</a></li>)}</ul></nav>
    <article className="space-y-20 pt-16">
      <Section id="overview"><div className={prose}><p>Yamanaka Lacquerware comes from the Yamanaka Onsen area of Kaga City in Ishikawa Prefecture. Woodturning is an important part of its identity: before a wooden vessel is coated, its rim, curves, and surface have already been shaped by a specialist.</p><p>The regional name covers a broad industry. Alongside wooden lacquerware, Yamanaka produces modern wares with resin bodies and a range of coatings. Understanding a piece begins with two questions: what is underneath, and how has the surface been finished?</p></div><Reading ids={[3, 4]} /></Section>
      <Section id="history"><div className={prose}><p>The traditional origin account places woodturners in Masago, upstream from Yamanaka Onsen, during the Tensho era of 1573–1592. Ishikawa Prefecture presents this as the reported origin of the craft, rather than proof of a single founding moment.</p><p>The technology center describes mobile woodturners settling in the area and gradually selling their wares to hot-spring visitors. Coating and maki-e techniques arrived from places including Aizu, Kyoto, and Kanazawa. The industry grew through a combination of local making and knowledge from elsewhere.</p><p>The prefectural account places woodturning in the present hot-spring district by 1715. It describes the development of decorative turning in the early nineteenth century and further advances as lathes improved in the early Meiji period. The fine surfaces seen today are the outcome of accumulated changes in tools and practice.</p></div><Reading ids={[1, 2]} /></Section>
      <Section id="why-here"><div className={prose}><p>The mountain setting matters, but wood alone does not explain a craft industry. People brought the skill to turn it into vessels; the hot-spring town brought customers; connections with other centers added ways to coat and decorate what was made.</p><p>That combination offers a useful way to read Yamanaka. A visitor sees a finished bowl in a shop, while behind it may be a network of woodturners, lacquer specialists, decorators, and businesses coordinating their work.</p></div><div className="mt-8 grid gap-6 sm:grid-cols-2">{[["A Place for Woodturners", "The origin account begins with skilled makers in the mountain settlement of Masago. The history of the place is inseparable from the people who knew how to work the material."], ["A Market in the Hot-Spring Town", "Visitors created a connection between workshops and buyers. Selling to people arriving in the town helped woodwork become part of a wider local economy."], ["Knowledge from Other Regions", "Incoming coating and decorative techniques broadened what the makers could offer. The tradition developed through contact as well as continuity."], ["Specialists Working Together", "A vessel can pass through several businesses. Coordinating those skills remains part of the industry today."]].map(([title, text]) => <div className={card} key={title}><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-stone-600">{text}</p></div>)}</div><CraftPhoto {...yamanakaPhotos.shop} layout="wide" /><Reading ids={[1, 2, 7]} /></Section>
      <Section id="materials"><div className={prose}><p>A regional name tells you where a tradition belongs; a product label tells you more about the particular object. Read the body material and coating separately, especially when choosing something for daily use.</p></div><div className="mt-8 grid gap-6 sm:grid-cols-2">{[["Wooden Bodies", "For a turned wooden vessel, the maker works with the grain, shape, and movement of the material. Look at the rim, foot, and any fitted lid as well as the color."], ["Modern Resin Bodies", "Modern lacquerware can use a resin body with natural lacquer or another coating, such as urethane. Its manufacture follows a different route from turning solid wood."], ["Visible Grain", "Fuki-urushi, or wiped lacquer, leaves the grain visible. The surface connects the character of the wood with the work that shaped it."], ["A Coated Surface", "Other finishes build up prepared surfaces and layers of lacquer. A covered grain is a different design choice, not evidence that the piece lacks skilled work."]].map(([title, text]) => <div className={card} key={title}><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-stone-600">{text}</p></div>)}</div><Reading ids={[4, 5, 9]} /></Section>
      <Section id="characteristics"><div className={prose}><p>Look closely at the shape before concentrating on decoration. A thin wall, a carefully formed lip, or a close-fitting lid can reveal decisions that a distant view misses.</p><p>Tate-kidori, often translated as vertical wood selection, is a characteristic approach to arranging the vessel within the wood. It supports precise work together with drying and finishing. It does not mean wood can never move, and makers also use horizontal selection for suitable objects.</p><p>Decorative turning, or kashoku-biki, cuts patterns into the surface. Fine grooves such as sensuji belong to the wooden form itself. Maki-e is a separate kind of decoration applied using lacquer and decorative powders; the two should not be confused simply because both enrich a surface.</p></div><Reading ids={[1, 3, 5]} /></Section>
      <Section id="production"><p className={prose}>This outline follows a wooden vessel. It separates the shaping of the body from the choice of finish, with decoration added only where the design calls for it.</p><CraftProcess id="yamanaka-process" eyebrow="Wood, tools, and finish" title="From Wood to a Finished Vessel" steps={steps} caveat="A guide to wooden turned wares, not a single recipe for every product. Wiped lacquer and a fully coated finish are different routes; modern resin-bodied wares begin with molding instead of woodturning." note="The finished surface depends on work that happens before coating. Material selection, drying, cutting, and finishing each contribute to how a vessel looks and feels in use." /><Reading ids={[1, 3, 5]} /></Section>
      <Section id="visit"><p className={prose}>Begin with an overview, then make time for the process that interests you most. Book workshop visits where required and confirm transport and opening days before setting out.</p><div className="mt-8 grid gap-6 sm:grid-cols-2">{places.map(place => <div className={card} key={place.name}><h3 className="text-xl font-semibold">{place.name}</h3><p className="mt-3 leading-7 text-stone-600">{place.description}</p><VisitLinks {...place} /></div>)}</div><Reading ids={[10, 11, 12]} /></Section>
      <Section id="today"><div className={prose}><p>The future of Yamanaka involves both products and the people able to make them. The technology center, opened in 1997, teaches woodturning alongside lacquer techniques and design. The cooperative also describes rental workshops supporting makers as they move toward independent work.</p><p>Contemporary design is another connection with new users. GATO MIKIO SHOUTEN describes collaboration with product and graphic designers, while Urushiza brings together current products from the region.</p><p>A 2023 industry case study reports challenges around aging craftspeople and succession, alongside shared digital tools for orders and production progress. Sustaining a craft includes coordinating work and reaching buyers as well as passing down techniques.</p></div><Reading ids={[6, 7, 8, 9, 10]} /></Section>
      <Section id="buying"><div className={prose}><p>Start with something you will use: a soup bowl, a cup, or a small serving dish. Consider capacity, weight, the feel of the rim, and how it sits in your hand. For a lidded vessel, check how the two parts fit.</p><p>Ask what the body and coating are made from, and how any pattern was created. A turned groove, a painted design, and printed decoration involve different methods. The price alone cannot explain those choices.</p><p>For ordinary wooden lacquerware, the technology center recommends mild dish detergent and a soft sponge, wiping away water, and storage away from prolonged direct sunlight. Keep it out of the microwave, dishwasher, and dish dryer. Some modern products are designed for these appliances, but use them only as their own instructions allow.</p><p>For a piece you hope to keep for many years, ask the seller about repair or recoating options. If taking it overseas, confirm packaging and shipping. A workshop experience may involve more finishing after your visit, or may not include a take-home object at all.</p></div><div className="mx-auto max-w-[480px]"><CraftPhoto {...yamanakaPhotos.bowls} layout="wide" /></div><Reading ids={[2, 4, 10]} /></Section>
      <Section id="faq"><div className="mt-8 divide-y divide-stone-200 border-y border-stone-200">{faqs.map(([question, answer]) => <details key={question} className="py-4"><summary className="min-h-11 cursor-pointer py-2 font-semibold leading-7 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">{question}</summary><p className="mt-4 leading-8 text-stone-700">{answer}</p></details>)}</div></Section>
      <Section id="sources"><p className={prose}>This guide draws on prefectural, technical-center, industry, tourism, and maker sources. Traditional origin accounts are presented as such. Most local references are in Japanese.</p><ul className="mt-8 space-y-6">{sources.map(([title, url, note], index) => <li id={`source-${index + 1}`} key={url} className="scroll-mt-6 border-l-2 border-stone-200 pl-4"><a href={url} target="_blank" rel="noopener noreferrer" className={`inline-block py-2 font-medium leading-7 ${link}`}>{title} <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a><p className="mt-2 text-sm leading-6 text-stone-600">{note}</p></li>)}</ul><p className="mt-8 text-sm leading-7 text-stone-600">Research reviewed October 2026. Check current visitor arrangements and follow the care instructions for your particular product.</p></Section>
    </article>
    <aside aria-label="Related craft guides" className="mt-16 border-t border-stone-200 pt-8"><h2 className="text-xl font-semibold">Explore Another Side of the Region</h2><p className="mt-4 leading-7 text-stone-700">Continue with Kutani Ware to explore a ceramic tradition connected with the Kaga region, through a different set of materials, techniques, and histories.</p><div className="mt-4 flex flex-wrap gap-6"><Link className={link} href="/en/crafts/kutani-ware">Kutani Ware →</Link><Link className={link} href="/en/crafts">All crafts →</Link></div></aside>
  </main>;
}
