import type { Metadata } from "next";
import Link from "next/link";
import BackToContents from "../_components/BackToContents";

export const metadata: Metadata = {
  title: "Kutani vs Arita vs Shigaraki: What’s the Difference? | Japan Crafts",
  description: "Compare Kutani, Arita, and Shigaraki Ware: their regions, materials, decoration, everyday use, and places to visit. Find a starting point for exploring Japanese ceramics.",
};
const link = "inline-block py-2 underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]";
const sections = [["at-a-glance", "At a Glance"], ["materials", "Materials and Making"], ["looking", "What to Look For"], ["choosing", "Choosing a First Piece"], ["visiting", "Choosing a Place to Visit"], ["faq", "FAQ"], ["sources", "Sources & Further Reading"]] as const;
const crafts = [
  {name:"Kutani Ware",region:"Ishikawa",material:"Principally porcelain",look:"Overglaze painting: bold colors, fine red lines, and gold are important traditions.",range:"From everyday tableware to elaborately painted works.",route:"kutani-ware"},
  {name:"Arita Ware",region:"Saga, Kyushu",material:"Porcelain",look:"Blue-and-white decoration, colored enamels, gold, and undecorated white porcelain.",range:"Many forms and decorative approaches, shaped by domestic use and overseas trade.",route:"arita-ware"},
  {name:"Shigaraki Ware",region:"Shiga",material:"Principally pottery, including high-fired stoneware",look:"Clay texture and firing effects in traditional wood-fired work; glazed pieces also belong to the region.",range:"Tableware, tea vessels, planters, garden objects, and architectural ceramics.",route:"shigaraki-ware"},
];
const faqs = [
  ["Which is best for everyday use?", "All three regions produce objects intended for everyday use. Choose a particular cup, bowl, or plate by its intended purpose, weight, shape, and care instructions. The regional name alone does not establish durability or suitability."],
  ["Can I identify a piece by its color?", "Color can suggest a tradition, but it is not proof of origin. Arita includes colorful enamel decoration, Kutani has many painting styles, and Shigaraki includes glazed wares. Look for the maker’s information and ask the seller about attribution."],
  ["Is Shigaraki always unglazed?", "No. It includes glazed products as well as work fired without an applied glaze. In wood firing, ash can also form a natural glaze on the clay surface."],
  ["Is Arita the same as Imari?", "The terms overlap historically but are not interchangeable in every context. Imari was a port associated with the distribution of porcelain from the wider production region. Our Arita guide explains Arita, Imari, and Ko-Imari in more detail."],
  ["Which is most expensive?", "There is no useful fixed ranking by region. Maker, age, provenance, technique, condition, and the amount of work involved can matter more than the regional label."],
];
export default function ComparisonPage() {
 return <main className="mx-auto max-w-4xl px-6 py-12 sm:py-20">
  <header><p className="text-sm uppercase tracking-[0.25em] text-stone-500">Japanese Ceramics · A Comparison Guide</p><h1 className="mt-4 text-4xl font-semibold leading-tight sm:text-5xl">Kutani vs Arita vs Shigaraki: What’s the Difference?</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-stone-600">Three production regions, many kinds of objects. Compare their materials and visual traditions, then follow the one that interests you.</p></header>
  <nav id="contents" aria-label="Article contents" className="mt-12 scroll-mt-6 border-y border-stone-200 py-6"><p className="mb-4 text-sm font-semibold uppercase tracking-wider">Contents</p><ul className="grid gap-2 sm:grid-cols-2">{sections.map(([id,label])=><li key={id}><a className={link} href={`#${id}`}>{label}</a></li>)}</ul></nav>
  <article className="space-y-20 pt-16 leading-8 text-stone-700">
   <section id="at-a-glance" className="scroll-mt-6"><h2 className="text-3xl font-semibold text-stone-900">At a Glance</h2><p className="mt-5">Kutani and Arita are principally porcelain traditions; Shigaraki offers a different starting point in pottery and the character of fired clay. But these names describe production regions and histories, not three rigid styles. Use the comparison as an introduction, not an identification test.</p><div className="mt-8 grid gap-6 md:grid-cols-3">{crafts.map(c=><div key={c.route} className="min-w-0 rounded-lg border border-stone-200 bg-white p-6"><p className="text-sm text-stone-500">{c.region}</p><h3 className="mt-2 text-xl font-semibold text-stone-900">{c.name}</h3><dl className="mt-5 space-y-4 text-sm leading-7">{[["Material",c.material],["Visual starting point",c.look],["Range",c.range]].map(([label,value])=><div key={label}><dt className="font-semibold">{label}</dt><dd className="mt-1">{value}</dd></div>)}</dl><Link className={`mt-4 ${link}`} href={`/en/crafts/${c.route}`}>Explore {c.name} →</Link></div>)}</div><BackToContents /></section>
   <section id="materials" className="scroll-mt-6"><h2 className="text-3xl font-semibold text-stone-900">Materials and Making</h2><div className="mt-5 space-y-6"><p>In Kutani’s overglaze-painted tradition, the porcelain body is fired before painters decorate its glazed surface. Further firing develops the colors. That sequence helps explain why the work of forming a vessel and painting it may involve different specialists.</p><p>Arita also includes overglaze decoration, alongside blue-and-white painting beneath the glaze and pieces that emphasize the porcelain body itself. Its production history connects raw materials and specialist skills with merchants, regional organization, and overseas buyers.</p><p>In Shigaraki, preparing a clay blend and shaping it for the intended object are central. Wood-fired pieces can develop ash deposits and variations in color, while glazed tableware and other products follow different processes. Not every Shigaraki piece is fired with wood.</p><p>These are differences of emphasis. Painting is not exclusive to one region, and firing is not simply an uncontrolled accident: makers choose materials, forms, and working methods.</p></div><BackToContents /></section>
   <section id="looking" className="scroll-mt-6"><h2 className="text-3xl font-semibold text-stone-900">What to Look For</h2><div className="mt-6 space-y-6"><div><h3 className="text-xl font-semibold text-stone-900">Kutani: follow the brush</h3><p className="mt-3">Look at the density of painted areas, the use of unpainted space, and the fineness of lines. Green-dominant Aote, delicate red painting, and richly decorated Shoza-style work offer very different experiences within one tradition.</p></div><div><h3 className="text-xl font-semibold text-stone-900">Arita: compare decoration and form</h3><p className="mt-3">Compare a blue-and-white dish with an enamel-painted or undecorated piece. Notice how a border, an open area, or the shape of the vessel changes the effect. “Arita” is broader than one export style or one palette.</p></div><div><h3 className="text-xl font-semibold text-stone-900">Shigaraki: look around the surface</h3><p className="mt-3">On traditional wood-fired work, compare the sides of an object: exposed clay, reddish firing color, and natural ash glaze can appear together. Then look at a glazed vessel or planter to see how much lies beyond that familiar appearance.</p></div></div><BackToContents /></section>
   <section id="choosing" className="scroll-mt-6"><h2 className="text-3xl font-semibold text-stone-900">Choosing a First Piece</h2><p className="mt-5">Start with something you will use. A favorite color may draw you to Kutani, a particular porcelain form to Arita, or a textured surface to Shigaraki. Those are personal starting points, not rules about who should buy each type.</p><ul className="mt-5 list-disc space-y-3 pl-6"><li>Hold the piece if possible: consider its weight, rim, handle, and balance.</li><li>Ask who made it and how it was formed, decorated, and fired.</li><li>Confirm that it is intended for food, display, or outdoor use as appropriate.</li><li>Check the exact product’s microwave, dishwasher, and cleaning instructions.</li></ul><p className="mt-6">Do not assume porcelain is always machine-safe, that a rough surface means a handmade object, or that one regional name guarantees a higher price or quality. Metallic decoration, glaze, construction, and intended use all matter. An antique or display object needs a different assessment from a new dinner plate.</p><BackToContents /></section>
   <section id="visiting" className="scroll-mt-6"><h2 className="text-3xl font-semibold text-stone-900">Choosing a Place to Visit</h2><div className="mt-6 space-y-6"><p><strong>Kutani:</strong> plan around the question that interests you. Kaga’s museums and kiln history, Komatsu’s clay production at CERABO KUTANI, and Nomi’s museums and workshops reveal different parts of a geographically spread industry.</p><p><strong>Arita:</strong> combine porcelain collections with the town’s production landscape and shops. The Kyushu Ceramic Museum, Izumiyama Quarry, and Arita Será provide different perspectives on materials, history, and trade.</p><p><strong>Shigaraki:</strong> combine the Traditional Industry Hall, a kiln-district walk, and the Ceramic Cultural Park. Together they connect historic production, working surroundings, and contemporary ceramics.</p><p>Choose the region that fits your wider journey rather than treating all three as nearby stops. Check opening days, transport, workshop reservations, language support, and shipping arrangements through the detailed guides below.</p></div><div className="mt-5 flex flex-wrap gap-5">{crafts.map(c=><Link key={c.route} className={link} href={`/en/crafts/${c.route}#visit`}>{c.name}: places to visit →</Link>)}</div><BackToContents /></section>
   <section id="faq" className="scroll-mt-6"><h2 className="text-3xl font-semibold text-stone-900">FAQ</h2><div className="mt-8 divide-y divide-stone-200 border-y border-stone-200">{faqs.map(([q,a])=><details key={q} className="py-4"><summary className="min-h-11 cursor-pointer py-2 font-semibold leading-7 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">{q}</summary><p className="mt-3 pb-2">{a}</p></details>)}</div><BackToContents /></section>
   <section id="sources" className="scroll-mt-6"><h2 className="text-3xl font-semibold text-stone-900">Sources & Further Reading</h2><p className="mt-5">This comparison brings together our three researched regional guides. Each includes sources for its history, production, visitor information, and care advice. Visual descriptions indicate important traditions, not a complete definition of every object made in a region.</p><ul className="mt-5 space-y-3">{crafts.map(c=><li key={c.route}><Link className={link} href={`/en/crafts/${c.route}#sources`}>{c.name}: guide and sources →</Link></li>)}</ul><p className="mt-6 text-sm text-stone-600">Reviewed September 2026. Confirm current visitor details and individual product instructions before travelling or buying.</p><BackToContents /></section>
  </article>
  <Link className={`mt-12 ${link}`} href="/en/crafts">← All crafts</Link>
 </main>;
}
