import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import BackToContents from "../_components/BackToContents";
import CraftProcess from "../_components/CraftProcess";
import CraftPhoto from "../_components/CraftPhoto";
import { shigarakiPhotos } from "./shigarakiPhotos";
import VisitLinks from "../_components/VisitLinks";

export const metadata: Metadata = {
  title: "Shigaraki Ware (信楽焼): Clay, History, Making & Travel Guide",
  description: "Discover Shigaraki Ware through its clay, kilns, tea vessels, tanuki figures, and changing industry, with places to visit and advice for choosing a piece.",
};

// Editorial basis: content/research/shigaraki.md. Image rights: shigaraki-images.md.
const sections = [
  ["overview", "Overview"], ["history", "History"],
  ["why-here", "Why Shigaraki?"], ["characteristics", "Characteristics"],
  ["tanuki", "More Than Tanuki"], ["production", "How Shigaraki Ware Is Made"],
  ["visit", "Where to Experience Shigaraki Ware"], ["today", "Shigaraki Ware Today"],
  ["buying", "Buying Guide"], ["faq", "FAQ"], ["sources", "Sources & Further Reading"],
] as const;
const sources = [
  ["Six Ancient Kilns — Shigaraki", "https://sixancientkilns.jp/shigaraki/", "Medieval origins, changing products, and the relationship with tea."],
  ["Shiga Prefecture — Shigaraki Ceramics", "https://www.pref.shiga.lg.jp/fd00/6496.html", "Clay resources and the range of industrial and household products."],
  ["Shigaraki Ceramic Industry Cooperative — About Shigaraki Ware", "https://www.593touki.jp/shigarakiyaki.html", "Clay properties and the surfaces created in firing."],
  ["Japan Traditional Crafts Aoyama Square — Shigaraki Ware", "https://kougeihin.jp/craft/0413/", "Materials and production; also records the traditional ancient-origin account."],
  ["Shigaraki Ceramic Industry Cooperative — Organization", "https://www.593touki.jp/association.html", "Shared material supply and the organization behind the industry."],
  ["Shigaraki Ceramic Industry Cooperative — Activities", "https://www.593touki.jp/services.html", "Material development and support for younger workers."],
  ["Shigaraki Ceramic Cultural Park — About", "https://www.sccp.jp/what-sccp-is/about-mori/", "Exhibitions, industry, and creative exchange."],
  ["Pottery Day — Shigaraki Ware", "https://yakimono.or.jp/sanchi/shigarakiyaki", "The modern development of tanuki figures and Fujiwara Tetsuzo."],
  ["Shigaraki Tourism Association — Town Walks", "https://www.e-shigaraki.org/discover/introduction/town/", "The kiln district and its streets."],
  ["Shigaraki Tourism Association — Experiences", "https://www.e-shigaraki.org/discover/spot/experience/", "Workshops and booking information."],
  ["Meizan — Product Manual", "https://www.meizan.co.jp/f/product-manual", "Manufacturer-specific care guidance; not a rule for every Shigaraki product."],
] as const;
const prose = "mt-5 space-y-6 leading-8 text-stone-700";
const card = "rounded-lg border border-stone-200 bg-white p-6";
const link = "underline underline-offset-4 hover:text-stone-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]";
function Section({ id, children }: { id: (typeof sections)[number][0]; children: ReactNode }) {
  return <section id={id} aria-labelledby={`${id}-heading`} className="scroll-mt-6"><h2 id={`${id}-heading`} className="text-3xl font-semibold">{sections.find(s => s[0] === id)?.[1]}</h2>{children}<BackToContents /></section>;
}
function Reading({ ids }: { ids: number[] }) {
  return <p className="mt-6 text-sm leading-7 text-stone-600">Reading for this section: {ids.map((id, i) => <span key={id}>{i > 0 && "; "}<a href={`#source-${id}`} className={link}>{sources[id - 1][0]}</a></span>)}.</p>;
}
const steps = [
  { number: "01", title: "Preparing the Clay", summary: "Blend material for the object.", description: "Raw clays are prepared, mixed with water, and kneaded. The blend must suit the intended form: the demands of a large garden vessel differ from those of a small cup. Clay preparation is part of the craft, not simply a matter of digging material from the ground." },
  { number: "02", title: "Forming", summary: "Build, throw, or use a mold.", description: "Makers shape clay on a wheel, build it by hand, or use molds. Large forms may be built up with coils and worked on the wheel. Different forming methods serve different objects; a regular shape alone does not tell you how a piece was made." },
  { number: "03", title: "Drying and Surface Work", summary: "Let the form settle.", description: "The formed object dries before firing. Depending on the design, its surface may be carved, impressed, or otherwise worked. Thickness and shape matter throughout this stage, especially for larger pieces." },
  { number: "04", title: "Glazing, Where Used", shortLabel: "Glazing", summary: "Choose a surface treatment.", optional: true, description: "A glazed piece may be bisque-fired before glaze is applied; some work also includes underglaze decoration. Work fired without an applied glaze follows a different route; wood ash may still form a natural glaze in the kiln. Shigaraki has both traditions, so glazing is not a compulsory stage for every object." },
  { number: "05", title: "Firing and Cooling", summary: "Heat transforms the surface.", description: "Firing turns the prepared clay into a ceramic object. In a wood-fired kiln, ash and the conditions around each piece can contribute to its surface. Other kiln types are also used. Temperatures and firing schedules vary with the clay, glaze, object, and kiln; after firing, the work cools before it is removed." },
];
const places = [
  { name: "Shigaraki Traditional Industry Hall", description: "Begin with the production region and its history. Displays offer a useful introduction before you visit shops and workshops.", website: "https://www.city.koka.lg.jp/6099.htm", mapQuery: "甲賀市信楽伝統産業会館", note: "Use the current city visitor information: older guides may refer to the former building." },
  { name: "Shigaraki Ceramic Cultural Park", description: "Explore ceramics as art as well as industry. The park brings together exhibitions, industrial products, and spaces for creative work.", website: "https://www.sccp.jp/what-sccp-is/about-mori/", mapQuery: "滋賀県立陶芸の森", note: "Check which exhibitions and facilities are open, and whether a visit or activity needs advance booking." },
  { name: "The Kiln Walking Trail", description: "Walk through the district where kilns and workshops are part of the town. Ceramic signs and traces of production give context to objects seen in shops.", website: "https://www.e-shigaraki.org/discover/introduction/town/", mapQuery: "信楽 窯元散策路", note: "Working premises are not automatically open to visitors. Follow signs and ask before entering or photographing." },
  { name: "Pottery Experiences", description: "Try hand-building or wheel work at a local workshop. Working with the material can change how you look at a finished vessel.", website: "https://www.e-shigaraki.org/discover/spot/experience/", mapQuery: "信楽 陶芸体験", note: "Confirm reservations, language support, firing time, and overseas shipping directly. Do not assume a finished piece can be taken home that day." },
];
const faqs = [
  ["Is Shigaraki Ware porcelain?", "Shigaraki is principally a pottery tradition, including high-fired unglazed wares, rather than a porcelain tradition like Arita. Check an individual product’s material rather than relying on its color alone."],
  ["Is all Shigaraki Ware unglazed?", "No. Work fired without an applied glaze is an important part of its history, and wood ash can form a natural glaze during firing, but glazed tableware, garden objects, and architectural ceramics also belong to the production region."],
  ["Are all pieces fired with wood?", "No. Wood-fired kilns remain part of the tradition, but other kiln types are used too. Ask the maker if the firing method is important to your choice."],
  ["Why are there so many tanuki figures?", "Tanuki became a widely recognized part of Shigaraki’s identity in the twentieth century. Their popularity is a modern chapter within a much longer history of making ceramics."],
  ["Can I use a microwave or dishwasher?", "Only if the instructions for that product allow it. A maker’s guidance for one range does not establish suitability for every Shigaraki piece. Microwave approval also does not mean oven or direct-heat approval."],
  ["Can I take a workshop piece home immediately?", "Usually a newly formed clay object still needs drying and firing. Confirm the completion date, collection arrangements, and shipping options before booking, particularly if you live outside Japan."],
];

export default function ShigarakiWarePage() {
  return <main className="mx-auto max-w-4xl px-6 py-12 sm:py-20">
    <header><p className="text-sm uppercase tracking-[0.25em] text-stone-500">Shiga · Pottery</p><h1 className="mt-4 text-4xl font-semibold sm:text-5xl">Shigaraki Ware <span className="whitespace-nowrap">(信楽焼)</span></h1><p className="mt-6 max-w-3xl text-xl leading-9 text-stone-600">How a region’s clay and skills found new purposes—from storage jars and tea vessels to garden pottery and contemporary design.</p></header>
    <CraftPhoto {...shigarakiPhotos.storageJar} layout="wide" preload />
    <nav id="contents" aria-label="Article contents" className="mt-12 scroll-mt-6 border-y border-stone-200 py-6"><p className="mb-4 text-sm font-semibold uppercase tracking-wider">Contents</p><ul className="grid gap-2 sm:grid-cols-2">{sections.map(([id, title]) => <li key={id}><a href={`#${id}`} className="inline-flex min-h-11 items-center text-stone-600 hover:text-stone-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">{title}</a></li>)}</ul></nav>
    <article className="space-y-20 pt-16">
      <Section id="overview"><div className={prose}><p>Shigaraki Ware is made in and around Shigaraki, in Koka, Shiga Prefecture. Its products range from cups and flower vessels to planters, garden objects, tiles, and ceramic panels. The name identifies a production region with many kinds of work, rather than one fixed appearance.</p><p>A rough clay surface or a tanuki figure—a ceramic depiction of a Japanese raccoon dog—may be your first encounter with Shigaraki. Both are ways into a larger story: how makers adapt material and skills to changing needs.</p></div><Reading ids={[2]} /></Section>
      <Section id="history"><div className={prose}><p>Shigaraki belongs to the Six Ancient Kilns, a group of historic Japanese pottery-producing regions. The group’s heritage account places the emergence of Shigaraki pottery around the thirteenth century, with technical influence from Tokoname. Early production included jars and grinding bowls. Shigaraki later developed its own forms and surfaces.</p><p>A traditional account traces its beginnings further back, to roof tiles made for Shigaraki Palace in the eighth century. That story should be distinguished from the medieval development of the pottery-producing region; it does not by itself establish an uninterrupted line of production.</p><p>Tea culture brought another way of valuing these objects. Everyday vessels could be selected for tea use, while makers also produced pieces for that purpose. Their significance came from how people used and appreciated them, as well as how they were made.</p><p>Later products included glazed household wares and charcoal braziers, known as hibachi. During the 1950s, makers expanded into planters as interest in ornamental plants grew. Architectural ceramics became another important direction. These products overlapped rather than replacing one another all at once: adapting existing skills to new uses is part of Shigaraki’s continuity.</p></div><CraftPhoto {...shigarakiPhotos.sakeJar} layout="wide" /><Reading ids={[1, 2, 4]} /></Section>
      <Section id="why-here"><div className={prose}><p>Clay was an essential resource. Shigaraki’s ceramic materials are associated with the ancient Lake Biwa deposits, rather than clay taken from the bed of today’s lake. But a usable material also depends on preparation: blending clays helps makers obtain the working properties they need.</p><p>The local cooperative describes clay blends with the plasticity and strength needed for large or thick-walled forms. A planter or garden vessel therefore tells a story about material preparation and forming skills as well as design.</p><p>Access to buyers mattered too. Connections with consumers in places such as Kyoto, and demand for tea vessels, helped give the work new uses and value. Shigaraki’s development is better understood as material, technical knowledge, and markets coming together than as the inevitable result of good clay alone.</p></div><Reading ids={[1, 2, 3]} /></Section>
      <Section id="characteristics"><p className={prose}>Begin with the surface, then ask how it relates to the object’s use. These features are especially useful when looking at wood-fired work made without an applied glaze; they do not describe every Shigaraki product.</p><div className="mt-8 grid gap-6 sm:grid-cols-3">{[["Fire Color", "Hiiro (火色・緋色) refers to reddish color developed in firing. It is part of the fired surface, rather than necessarily a painted decoration."], ["Natural Ash Glaze", "Ash from burning wood can react with the surface to form glassy areas. Look for the relationship between these deposits and the exposed clay."], ["A Varied Surface", "Darkened areas and changes in texture contribute to the object’s appearance. Compare different sides instead of judging it from a single front view."]].map(([title, text]) => <div className={card} key={title}><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-stone-600">{text}</p></div>)}</div><Reading ids={[3]} /></Section>
      <Section id="tanuki"><div className={prose}><p>The tanuki figures seen outside shops are a comparatively recent part of Shigaraki’s long history. An industry account associates their development with Fujiwara Tetsuzo and his work in Shigaraki in the 1930s. Their wider recognition grew in the twentieth century.</p><p>Enjoy them as one strand of the town’s ceramic culture, then look beyond them: a glazed cup, a large planter, and a ceramic architectural surface reveal other ways the same production region serves everyday life.</p></div><Reading ids={[8, 2]} /></Section>
      <Section id="production"><p className={prose}>There is no single sequence for every Shigaraki object. This outline distinguishes shared stages from surface treatments that depend on the piece.</p><CraftProcess id="shigaraki-process" eyebrow="Clay to ceramic" title="Material, Form, and Fire" steps={steps} caveat="A general guide, not a recipe for every workshop. Glazed and unglazed work take different routes, and firing schedules vary." note="The surface begins with decisions made well before firing: the clay blend, the form, and the chosen treatment all contribute to the finished object." /><Reading ids={[4]} /></Section>
      <Section id="visit"><p className={prose}>Combine a museum visit with a walk through the kiln district. Confirm current opening days, exhibitions, and transport before setting out.</p><div className="mt-8 grid gap-6 sm:grid-cols-2">{places.map(place => <div key={place.name} className={card}><h3 className="text-xl font-semibold">{place.name}</h3><p className="mt-3 leading-7 text-stone-600">{place.description}</p><VisitLinks {...place} /></div>)}</div></Section>
      <Section id="today"><div className={prose}><p>Shigaraki’s industry includes shared infrastructure as well as individual workshops. The ceramic cooperative supplies materials and supports development work and younger people entering the industry. This network helps explain why a production region is more than a collection of independent artists.</p><p>The Shigaraki Ceramic Cultural Park adds another dimension. Opened in 1990, it brings exhibitions, industrial ceramics, and creative activity together. Contemporary artistic work and everyday manufacturing can be considered alongside each other, rather than treated as separate histories.</p></div><Reading ids={[5, 6, 7]} /></Section>
      <Section id="buying"><div className={prose}><p>For a first piece, begin with an intended use. Hold a cup, consider its weight and rim, or check the scale of a planter against the place where it will stand. Ask who made it, how it was formed and fired, and how it should be cared for.</p><p>For tableware, check the product’s instructions for washing, drying, and heat exposure. Meizan, for example, advises thorough drying before storage and discourages dishwasher use for its tableware. Those instructions should not be generalized to every maker.</p><p>Unglazed pieces may need particular care around oily food. Ask whether staining is expected and whether any preparation is recommended. For garden pottery, confirm outdoor suitability with the seller instead of assuming every large ceramic object can stay outside year-round.</p></div><Reading ids={[11]} /></Section>
      <Section id="faq"><div className="mt-8 divide-y divide-stone-200 border-y border-stone-200">{faqs.map(([question, answer]) => <details key={question} className="py-4"><summary className="min-h-11 cursor-pointer py-2 font-semibold leading-7 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">{question}</summary><p className="mt-4 leading-8 text-stone-700">{answer}</p></details>)}</div></Section>
      <Section id="sources"><p className={prose}>These official, industry, and maker sources inform this guide. Origin stories are distinguished from the medieval history of the production region. Visitor information and product instructions should be checked with the relevant organization.</p><ul className="mt-8 space-y-6">{sources.map(([title, url, note], index) => <li id={`source-${index + 1}`} key={url} className="scroll-mt-6 border-l-2 border-stone-200 pl-4"><a href={url} target="_blank" rel="noopener noreferrer" className={`inline-block py-2 font-medium leading-7 ${link}`}>{title} <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a><p className="mt-2 text-sm leading-6 text-stone-600">{note}</p></li>)}</ul><p className="mt-8 text-sm leading-7 text-stone-600">Research reviewed September 2026. Most local sources are in Japanese. Check current visitor arrangements and product-care instructions with the institution or maker.</p></Section>
    </article>
    <aside aria-label="Related craft guides" className="mt-16 border-t border-stone-200 pt-8"><h2 className="text-xl font-semibold">Explore Other Ceramic Traditions</h2><p className="mt-4 leading-7 text-stone-700">How do these traditions differ? <a href="/en/crafts/kutani-vs-arita-vs-shigaraki" className="underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#355c49]">Compare Kutani, Arita, and Shigaraki</a> through their materials, appearance, and places of origin.</p><div className="mt-4 flex flex-wrap gap-6"><Link className={link} href="/en/crafts/kutani-ware">Kutani Ware →</Link><Link className={link} href="/en/crafts/arita-ware">Arita Ware →</Link><Link className={link} href="/en/crafts">All crafts →</Link></div></aside>
  </main>;
}
